#!/bin/bash
# This script prints the command line arguments to a new tab in Chrome
if [ -f /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome ] && [ -n $(command -v google-chrome) ]; then
  alias google-chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $@"
fi
function chrint () {
  B64=$(echo "<meta charset=utf8><style>body {font-family: sans-serif;display: flex; align-items: center; justify-content: center; font-size: 3em;}</style>$@" | base64)
  google-chrome "data:text/html;base64,$B64"
}
