#!/bin/bash
# This script prints the command line arguments to a new tab in Chrome
B64=$(echo "<meta charset=utf8><style>body {font-family: sans-serif;display: flex; align-items: center; justify-content: center; font-size: 3em;}</style>$@" | base64) 
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome "data:text/html;base64,$B64"
