#!/bin/bash

DIR="$(dirname "$0")"
JAR="$DIR/assets/closure-stylesheets.jar"
CODE=""

if [ $# -eq 0 ]; then
  CODE=$(cat /dev/stdin)
else
  for file; do
    CODE="$CODE 
    $(cat "$file")"
  done
fi

echo "$CODE" | java -jar "$JAR" /dev/stdin
