#!/usr/bin/env python3
from sys import stdout, path, argv
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter
from matplotlib.dates import DateFormatter


dates = []
values = []

filename = argv[1] if len(argv) > 1 else "/dev/stdin"
f = open(filename)

while line := f.readline():
    date, value = line.strip().split(",")
    print(date)
    dates.append(np.datetime64(date))
    values.append(float(value))

plt.gca().yaxis.set_major_formatter(StrMethodFormatter('{x:,.1f}'))
# plt.gca().xaxis.set_major_formatter(DateFormatter("%d. %b"))
plt.plot(dates, values)
# plt.figure(figsize=(8, 6), dpi=80)
plt.savefig(stdout.buffer, format="svg")
