#!/bin/zsh
if [[ `uname` = "Linux" ]]; then
  alias say="spd-say"
  SHORT_BREAK="2"
  SHORT_AFTER_LONG_BREAK="4"
  LONG_BREAK="3"
elif [[ `uname` = "Darwin" ]]; then
  alias say="say -v Alex"
  SHORT_BREAK="1"
  SHORT_AFTER_LONG_BREAK="1"
  LONG_BREAK="3"
fi
say "People think its funny but its really hot and runny"
sleep $SHORT_AFTER_LONG_BREAK
say "Diarrhea"
sleep $SHORT_BREAK
say "Diarrhea"
sleep $LONG_BREAK
say "People think its gross but its really good on toast"
sleep $SHORT_AFTER_LONG_BREAK
say "Diarrhea"
sleep $SHORT_BREAK
say "Diarrhea"
