#!/bin/zsh
if [[ `uname` = "Linux" ]]; then
  alias say="spd-say"
elif [[ `uname` = "Darwin" ]]; then
  alias say="say -v Alex"
fi
say "People think its funny, but its really hot and runny"
sleep 1
say "Diarrhea"
sleep 1
say "Diarrhea"
sleep 3
say "People think its gross, but its really good on toast"
sleep 1
say "Diarrhea"
sleep 1
say "Diarrhea"
