#!/bin/bash
read "Before proceeding, make sure you have an open root shell, so that you can fix the sudo system if it breaks. Press ENTER to confirm that you have an active root shell opened."
sudo sed -i '' '2i\
auth sufficient pam_tid.so
' /etc/pam.d/sudo
echo "**NB**! Please test that the sudo command still works. If it does not, the file /etc/pam.d/sudo has probably been broken. Use a sudo shell to edit and fix it."

