#!/usr/bin/env zsh
source ~/.zshrc
cd ~/Git
for dir in *; do
  cd "$dir"; echo; echo; python -c "print('$dir:'.ljust(40), end='')"
  git remote get-url origin && git fetch origin && git diff --name-only "origin/$(current_branch)" | cat || git status
  cd ~/Git
done
