#!/bin/bash
name=$(git config --global user.name)
email=$(git config --global user.email)
git config --global user.email "None"
fake_name=${@:-"Formatter"}
git config --global user.name "$fake_name"
printf "Temporarily changed Git identity. Press enter to change back."
read
git config --global user.email "$email"
git config --global user.name "$name"
