#!/bin/bash
# Syncs all git repos in a directory
# Takes one optional argument: a string to search for in the repos origin url (e.g. "github")
# Available flags:
#   --no-push  Do not push after pulling
start_dir=$(pwd)
if [[ "$@" == *"--no-push"* ]]; then
  printf "Pulling repositories with a origin url that contains $1"
  NO_PULL="true"
else
  printf "Pulling and pushing repositories with a origin url that contains $1"
fi
for dir in *; do
  cd "$start_dir"
  if [ -d "$dir" ]; then
    cd "$dir"
    if git remote get-url origin > /dev/null 2> /dev/null; then
      if git remote get-url origin | grep -q "$1"; then
        printf "\n\nDo you want to sync $dir? [Y/n] "
        read
        if ! [[ $REPLY =~ ^[Nn]$ ]]; then
          header "Syncing $dir"
          git pull
          if [ "$NO_PULL" != "true" ]; then
            git push
            git pull
          fi
        fi
      fi
    fi
  fi
done
