#!/usr/bin/env python3
import os
from sys import argv
if len(argv) < 3:
    print("To use this script you need to supply the name of the new VirtualHost as the first command line argument and the DocumentRoot as the second")
    exit(1)
conf = """
<VirtualHost *:80>
    DocumentRoot "{directory}"
    ServerName {name}
    <Directory "{directory}">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
""".format(directory=argv[2], name=argv[1])
if os.path.isdir("/etc/apache2/sites-available/"):
    open("/etc/apache2/sites-available/"+argv[1]+".conf", "w").write(conf)
    os.system("a2ensite "+argv[1])
elif os.path.isfile("/etc/apache2/extra/httpd-vhosts.conf"):
    open("/etc/apache2/extra/httpd-vhosts.conf", "a").write(conf)
else:
    print("No compatible apache version found")
    exit(1)
open("/etc/hosts", "a").write("127.0.0.1 "+argv[1])
