#!/bin/bash 

git init
python3 -m virtualenv env
git ignore env
source env/bin/activate
pip install django
django-admin startproject $1
python $1/manage.py startapp $1

echo "Type 'source env/bin/activate' to activate virtual environment (for testing, developing and running server)"
