#!/bin/bash

echo "Name:"
read NAME
echo "Icon:"
read ICON
echo "Command to execute:"
read EXEC

echo "
[Desktop Entry]
Type=Application
Terminal=false
Icon=$ICON
Name=$NAME
Exec=$EXEC
Categories=Utility;
"
