#!/bin/bash

echo -n "Name:  "
read NAME
echo -n "Icon:  "
read ICON
echo -n "Command to execute:  "
read EXEC

echo "
[Desktop Entry]
Type=Application
Terminal=false
Icon=$ICON
Name=$NAME
Exec=$EXEC
Categories=Utility;
"
