#!/usr/bin/env python3
import requests, sys, json, os, simplejson
CONFIG_FILE_PATH = os.path.expanduser("~/.assistantrc")
CONFIG = json.load(CONFIG_FILE_PATH) if os.path.isfile(CONFIG_FILE_PATH) else {}
URL = CONFIG.get("url", "http://10.0.1.2:2002/assistant")
USER = CONFIG.get("user", "tordjohanespe")

command = " ".join(sys.argv[1:])
post_data = { "command": command, "user": USER }
headers = { "content-type": "application/json" }
req = requests.post(URL, data=json.dumps(post_data), headers=headers)
try:
    print(req.json().get("response", req.json()))
except simplejson.errors.JSONDecodeError:
    print(req.text)
