#!/bin/bash

if [ "$1" = "on" ]; then
  NEWVAL="false"
  OLDVAL="true"
elif [ "$1" = "off" ]; then
  NEWVAL="true"
  OLDVAL="false"
else
  echo "This command requires an argument. Use \"on\" to detect other operating systems and add them to the GRUB menu, and \"off\" to not detect other operating systems."
  exit 1
fi

if [ -f /etc/default/grub ]; then
  if grep -q DISABLE_OS_PROBER /etc/default/grub; then
    sudo sed -i "s/GRUB_DISABLE_OS_PROBER=$OLDVAL/GRUB_DISABLE_OS_PROBER=$NEWVAL/" /etc/default/grub
  else
    echo "GRUB_DISABLE_OS_PROBER=$NEWVAL" | sudo tee -a /etc/default/grub
  fi
else
  echo "Could not find GRUB configuration file"
  exit 1
fi

sudo update-grub
