#!/bin/bash
echo "<table>"
while read line
do
  echo "$line" | column -t | awk 'BEGIN{print "  <tr>"} {for(i=1;i<=NF;i++)print "    <td>" $i"</td>"} END{print "  </tr>"}'
done < "${1:-/dev/stdin}"
echo "</table>"
