#!/usr/bin/env python3
import fileinput, re

print("<table>")
for line in fileinput.input():
    print(" <tr>")
    for col in re.compile("(  |	|: )").split(line.strip()):
        print("     <td>"+col+"</td>")
    print(" </tr>")
print ("</table>")
